CREATE DATABASE dbMarket
GO

USE dbMarket
GO

CREATE TABLE PERSONA
(
    IDPER INT IDENTITY(1,1),
    DNIPER CHAR(8),
    NOMPER VARCHAR(100),
    APEPER VARCHAR(100),
	EMAPER VARCHAR(100),
	CELPER CHAR(9),
	TIPPER CHAR(2),
    ESTPER CHAR(1) DEFAULT 'A', -- Agrega por default el estado A (activo)
	FECNACPER DATE,
    CONSTRAINT PER_PK PRIMARY KEY (IDPER) -- Definiendo clave principal
)
GO

CREATE TABLE CATEGORIA
(
	IDCAT INT IDENTITY(1,1),
	NOMCAT VARCHAR (50),
	CONSTRAINT CAT_PK PRIMARY KEY (IDCAT) -- Definiendo clave principal
)
GO

CREATE TABLE PRODUCTO 
(
    CODPRO CHAR (6),
    NOMPRO VARCHAR (50),
    PREPRO DECIMAL(8,2),
    STOCKPRO INT, 
    IDCAT INT,
	ESTPRO CHAR(1) DEFAULT 'A',
    CONSTRAINT PRO_PK PRIMARY KEY (CODPRO)
)
GO

CREATE TABLE VENTA 
(
    IDVENT INT IDENTITY(1,1),
	FECVEN DATETIME DEFAULT GETDATE(), 
    IDPERVEN INT,
    IDPERCLI INT,
	TIPPAGVEN CHAR(1),
    ESTVEN CHAR(1) DEFAULT 'A',
    CONSTRAINT VEN_PK PRIMARY KEY (IDVENT)
)
GO

CREATE TABLE VENTA_DETALLE
(
	IDVENTDET INT IDENTITY(1,1),
	IDVENT INT,
	CODPRO CHAR(6),
	CANVENDET INT,
	CONSTRAINT IDVENTDET_PK PRIMARY KEY (IDVENTDET) -- Definiendo clave principal
)
GO

--ESTABLECEMOS LAS RELACIONES--

ALTER TABLE PRODUCTO 
ADD CONSTRAINT PRODUCTO_CATEGORIAFK
FOREIGN KEY (IDCAT)
REFERENCES CATEGORIA (IDCAT)
GO

ALTER TABLE VENTA 
ADD CONSTRAINT VENTA_VENDEDOR_FK FOREIGN KEY (IDPERVEN)
REFERENCES PERSONA (IDPER)
GO

ALTER TABLE VENTA 
ADD CONSTRAINT VENTA_CLIENTE_FK FOREIGN KEY (IDPERCLI)
REFERENCES PERSONA (IDPER)
GO

ALTER TABLE VENTA_DETALLE
ADD CONSTRAINT VENTA_DETALLE_VENTA_FK FOREIGN KEY (IDVENT)
REFERENCES VENTA (IDVENT)
GO

ALTER TABLE VENTA_DETALLE
ADD CONSTRAINT VENTA_DETALLE_PRODUCTO_FK FOREIGN KEY (CODPRO)
REFERENCES PRODUCTO (CODPRO)
GO

--INSERTAMOS LOS REGISTROS--

SET DATEFORMAT dmy 
GO

INSERT INTO PERSONA
(DNIPER,NOMPER,APEPER,CELPER,TIPPER,FECNACPER)
VALUES
('77889955','Alberto', 'Solano Pariona','998456321', 'juan.palomino@gmail.com', 'V','10/02/1970'),
('45781233','Alicia', 'García Campos','978899552', 'alicia.garcia.@gmail.com', 'C','20/03/1980'),
('15487922','Juana', 'Ávila Chumpitaz','976889455', 'juana.avila@gmail.com', 'C','06/06/1986'),
('22116633','Ana', 'Enrique Flores', '927000955','ana.enriquez@gmail.com', 'V','10/02/1970'),
('88741589','Claudia', 'Perales Ortíz','907288935', 'claudia.perales@yahoo.com', 'C','25/07/1981'),
('45122587','Mario', 'Barrios Martinez', '947849945','mario.barrios@outlook.com', 'C','10/10/1987'),
('15258564','Brunela', 'Tarazona Guerra', '927869905','brunela.tarazona@gmail.com', 'C','06/06/1990')
GO

SELECT*FROM PERSONA
